import Script from 'next/script'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import {useEffect, useState} from "react";


function useWasm(path: string) {
    const [state, setState] = useState<[any, boolean, Error | null]>([null, true, null])
    useEffect(() => {
        async function getWasm(path: string) {
            try {
                // @ts-ignore
                const go = new Go(); // Defined in wasm_exec.js
                go.importObject.env = {
                    'add': function(x: number, y: number) {
                        return x + y
                    }
                }
                const WASM_URL = path;

                var wasm;

                if ('instantiateStreaming' in WebAssembly) {
                    const obj = await WebAssembly.instantiateStreaming(fetch(WASM_URL), go.importObject)
                    wasm = obj.instance;
                    go.run(wasm);
                    return wasm.exports
                } else {
                  const resp = await fetch(WASM_URL)
                  const bytes = await resp.arrayBuffer()
                  const obj = await WebAssembly.instantiate(bytes, go.importObject)
                  wasm = obj.instance;
                  go.run(wasm);
                  return wasm.exports
                }
            } catch (e) {
                console.log(e);
                return {}
            }
        }

        getWasm(path)
            .then((exp) => {
                setState([exp, false, null])
            })
            .catch((err) => {
                setState([null, false, err])
            })
    }, [path])
    return state
}


export default function Home() {
    const mod = useWasm('/golang-nextjs.wasm')
    console.log('wasm', mod)
    return (
        <div className={styles.container}>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <Script strategy={'beforeInteractive'} src="/wasm_exec.js"/>

            <main className={styles.main}>
                <h1 className={styles.title}>
                    Welcome to <a href="https://nextjs.org">Next.js!</a>
                </h1>

                <p className={styles.description}>
                    Get started by editing{' '}
                    <code className={styles.code}>pages/index.tsx</code>
                </p>

                <div className={styles.grid}>
                    <a href="https://nextjs.org/docs" className={styles.card}>
                        <h2>Documentation &rarr;</h2>
                        <p>Find in-depth information about Next.js features and API.</p>
                    </a>

                    <a href="https://nextjs.org/learn" className={styles.card}>
                        <h2>Learn &rarr;</h2>
                        <p>Learn about Next.js in an interactive course with quizzes!</p>
                    </a>

                    <a
                        href="https://github.com/vercel/next.js/tree/canary/examples"
                        className={styles.card}
                    >
                        <h2>Examples &rarr;</h2>
                        <p>Discover and deploy boilerplate example Next.js projects.</p>
                    </a>

                    <a
                        href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
                        target="_blank"
                        rel="noopener noreferrer"
                        className={styles.card}
                    >
                        <h2>Deploy &rarr;</h2>
                        <p>
                            Instantly deploy your Next.js site to a public URL with Vercel.
                        </p>
                    </a>
                </div>
            </main>

            <footer className={styles.footer}>
                <a
                    href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
                    target="_blank"
                    rel="noopener noreferrer"
                >
                    Powered by{' '}
                    <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16}/>
          </span>
                </a>
            </footer>
        </div>
    )
}
